// LoreGraph — mock data based on "Pride and Prejudice" by Jane Austen
// (Project Gutenberg eBook #1342, public domain)

window.LG_DATA = {
  user: {
    name: "Yunyue Li",
    handle: "@yunyueli",
    plan: "Researcher · Anthropic",
    budgetUsed: 14.27,
    budgetCap: 50.00,
  },

  books: [
    {
      id: "pap",
      title: "Pride and Prejudice",
      titleZh: "傲慢与偏见",
      author: "Jane Austen",
      year: 1813,
      tokens: 162400,
      chapters: 61,
      language: "EN",
      status: "verified",          // ingested · running · verified · failed
      matchRate: 0.97,
      entities: 38,
      edges: 124,
      glucose: 412,
      coverTone: "gold",
      provider: "anthropic",
      lastRun: "2026-05-26 09:14",
      cost: 2.84,
      active: true,
    },
    {
      id: "rose",
      title: "The Name of the Rose",
      titleZh: "玫瑰之名",
      author: "Umberto Eco",
      year: 1980,
      tokens: 198400,
      chapters: 7,
      language: "EN",
      status: "running",
      matchRate: null,
      progress: 0.64,
      currentPass: 5,
      entities: 412,
      edges: null,
      glucose: null,
      coverTone: "rust",
      provider: "deepseek",
      lastRun: "2026-05-27 09:18",
      cost: 4.18,
    },
    {
      id: "frank",
      title: "Frankenstein",
      titleZh: "弗兰肯斯坦",
      author: "Mary Shelley",
      year: 1818,
      tokens: 78320,
      chapters: 24,
      language: "EN",
      status: "verified",
      matchRate: 0.96,
      entities: 187,
      edges: 342,
      glucose: 680,
      coverTone: "moss",
      provider: "anthropic",
      lastRun: "2026-05-20 11:30",
      cost: 2.04,
    },
    {
      id: "drac",
      title: "Dracula",
      titleZh: "德古拉",
      author: "Bram Stoker",
      year: 1897,
      tokens: 161200,
      chapters: 27,
      language: "EN",
      status: "verified",
      matchRate: 0.95,
      entities: 246,
      edges: 522,
      glucose: 1108,
      coverTone: "ink",
      provider: "qwen",
      lastRun: "2026-05-18 22:11",
      cost: 1.92,
    },
    {
      id: "alice",
      title: "Alice's Adventures in Wonderland",
      titleZh: "爱丽丝梦游仙境",
      author: "Lewis Carroll",
      year: 1865,
      tokens: 27340,
      chapters: 12,
      language: "EN",
      status: "ingested",
      matchRate: null,
      entities: 0,
      edges: 0,
      glucose: 0,
      coverTone: "yellow",
      provider: "anthropic",
      lastRun: null,
      cost: 0,
    },
    {
      id: "mob",
      title: "Moby-Dick",
      titleZh: "白鲸",
      author: "Herman Melville",
      year: 1851,
      tokens: 209100,
      chapters: 135,
      language: "EN",
      status: "failed",
      matchRate: 0.91,
      entities: 89,
      edges: 0,
      glucose: 0,
      coverTone: "deep",
      provider: "anthropic",
      lastRun: "2026-05-22 04:08",
      cost: 1.18,
      failedAt: "Pass-7 · match rate 0.91 < 0.95 threshold",
    },
  ],

  // Active book (Pride and Prejudice) entities
  entities: [
    // Agents (Bennets)
    { id: "e01", type: "agent", name: "Elizabeth Bennet", zh: "伊丽莎白·班纳特",
      aliases: ["Elizabeth","Lizzy","Eliza","Miss Bennet (the second)","Miss Elizabeth"],
      mentions: 642, conf: 0.99, chapters: [1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61],
      summary: "班纳特家第二女，机智、独立、有判断力。全书焦点视角；从对 Darcy 的偏见走向自省与爱。" },
    { id: "e02", type: "agent", name: "Mr. Darcy", zh: "达西先生",
      aliases: ["Darcy","Fitzwilliam Darcy","Mr. Fitzwilliam Darcy","my master"],
      mentions: 418, conf: 0.99, chapters: [3,4,5,6,7,8,9,10,11,12,15,16,17,18,19,21,23,25,26,27,28,30,31,32,33,34,35,36,37,42,43,44,45,46,47,48,50,52,53,54,55,56,57,58,59,60,61],
      summary: "Pemberley 庄园主，年收入万英镑。初见时被叙述者眼中视为傲慢；letter 之后形象彻底翻转。" },
    { id: "e03", type: "agent", name: "Jane Bennet", zh: "简·班纳特",
      aliases: ["Jane","Miss Bennet","my dear Jane","the eldest"],
      mentions: 268, conf: 0.98, chapters: [1,2,3,4,5,6,7,8,9,10,11,12,13,17,18,21,22,23,24,25,26,33,40,46,48,49,50,51,55,57,59,61],
      summary: "班纳特家长女，温柔、不轻易表达。与 Bingley 的关系是主副线之一。" },
    { id: "e04", type: "agent", name: "Mr. Bingley", zh: "宾利先生",
      aliases: ["Bingley","Charles Bingley","Mr. Charles Bingley"],
      mentions: 174, conf: 0.98, chapters: [1,3,4,5,6,7,8,9,10,11,12,13,17,21,55,57,59,61],
      summary: "Darcy 之友，租下 Netherfield Park。性情温厚、易受朋友左右。" },
    { id: "e05", type: "agent", name: "Mr. Bennet", zh: "班纳特先生",
      aliases: ["Mr. Bennet","my father","papa"],
      mentions: 122, conf: 0.97, chapters: [1,2,5,7,12,13,18,20,23,41,47,48,49,57,59,60],
      summary: "班纳特家家主，反讽、消极的旁观者；在 Lydia 私奔后短暂行动。" },
    { id: "e06", type: "agent", name: "Mrs. Bennet", zh: "班纳特太太",
      aliases: ["my mother","mamma","Mrs. Bennet"],
      mentions: 168, conf: 0.97, chapters: [1,2,3,4,7,9,13,18,20,23,41,42,47,49,53,55,57,59,61],
      summary: "毕生事业是把五个女儿嫁出去。神经、夸张、推动 plot 的喜剧引擎。" },
    { id: "e07", type: "agent", name: "Lydia Bennet", zh: "莉迪亚·班纳特",
      aliases: ["Lydia","my sister Lydia"],
      mentions: 144, conf: 0.96, chapters: [2,7,9,11,12,18,39,41,46,47,48,49,50,51,52,53],
      summary: "班纳特家最幼女，十五岁；浮浅、冒失。与 Wickham 的私奔事件是全书结构枢纽。" },
    { id: "e08", type: "agent", name: "Mary Bennet", zh: "玛丽·班纳特",
      aliases: ["Mary"],
      mentions: 22, conf: 0.94, chapters: [2,5,6,7,8,11,12,18,47],
      summary: "班纳特家中间女，书呆子；偏好朗读箴言，几无 plot 作用。" },
    { id: "e09", type: "agent", name: "Kitty Bennet", zh: "凯瑟琳·班纳特",
      aliases: ["Catherine Bennet","Kitty","Catherine"],
      mentions: 38, conf: 0.93, chapters: [2,7,8,11,12,18,39,41,47,48],
      summary: "班纳特家第四女，依附于 Lydia；Lydia 走后逐渐成长。" },
    { id: "e10", type: "agent", name: "Mr. Wickham", zh: "韦克翰先生",
      aliases: ["Wickham","George Wickham","that man","that worthless young man"],
      mentions: 142, conf: 0.97, chapters: [15,16,17,18,21,24,25,27,34,35,36,39,41,46,47,48,49,50,51,52,53,57,61],
      summary: "民兵团军官，魅力外表掩盖赌债与丑闻。诱拐 Lydia 是其多次企图之一。" },
    { id: "e11", type: "agent", name: "Mr. Collins", zh: "柯林斯先生",
      aliases: ["Collins","William Collins","my cousin","my cousin Collins"],
      mentions: 108, conf: 0.97, chapters: [13,14,15,16,17,18,19,20,21,22,23,28,29,30,32,35,48,57,60],
      summary: "Mr. Bennet 的远房表弟，Longbourn 限定继承人；牧师；屈从于 Lady Catherine。" },
    { id: "e12", type: "agent", name: "Lady Catherine de Bourgh", zh: "凯瑟琳·德·包尔夫人",
      aliases: ["Lady Catherine","her ladyship","my aunt"],
      mentions: 78, conf: 0.98, chapters: [13,14,16,28,29,30,31,32,33,34,35,36,37,48,52,56,57],
      summary: "Darcy 的姨母，Rosings Park 庄园主；专横，期望 Darcy 与女儿联姻。" },
    { id: "e13", type: "agent", name: "Charlotte Lucas", zh: "夏洛特·卢卡斯",
      aliases: ["Charlotte","Miss Lucas","Mrs. Collins"],
      mentions: 96, conf: 0.97, chapters: [3,5,6,7,18,19,22,26,27,28,29,30,32,38,57],
      summary: "Elizabeth 挚友；27 岁未嫁，务实接受 Collins 的求婚。婚姻观与 Elizabeth 形成对照。" },
    { id: "e14", type: "agent", name: "Caroline Bingley", zh: "卡罗琳·宾利",
      aliases: ["Miss Bingley","Caroline","Bingley's sister"],
      mentions: 64, conf: 0.95, chapters: [4,6,7,8,9,10,11,17,18,21,23,25,26,45,54],
      summary: "Bingley 的妹妹，企图嫁给 Darcy 并阻挠 Jane；反派 archetype。" },
    { id: "e15", type: "agent", name: "Georgiana Darcy", zh: "乔治安娜·达西",
      aliases: ["Miss Darcy","Georgiana","my sister"],
      mentions: 28, conf: 0.96, chapters: [25,35,44,45,46,52,60],
      summary: "Darcy 的妹妹，十六岁；性情害羞。Wickham 曾企图诱拐她（letter 揭示）。" },
    { id: "e16", type: "agent", name: "Mr. Gardiner", zh: "嘉丁纳先生",
      aliases: ["my uncle","Mr. Gardiner","Edward Gardiner"],
      mentions: 52, conf: 0.96, chapters: [25,26,27,42,43,44,45,46,47,48,49,50,52],
      summary: "Mrs. Bennet 的弟弟，伦敦商人；与妻子带 Elizabeth 游历，间接促成 Pemberley 重逢。" },
    { id: "e17", type: "agent", name: "Mrs. Gardiner", zh: "嘉丁纳太太",
      aliases: ["my aunt","Mrs. Gardiner"],
      mentions: 64, conf: 0.96, chapters: [25,26,27,42,43,44,45,46,49,50,52],
      summary: "Elizabeth 的姨母与精神导师；Pemberley 之行的女主角；后期书信揭示真相的关键信源。" },
    { id: "e18", type: "agent", name: "Colonel Fitzwilliam", zh: "费茨威廉上校",
      aliases: ["Colonel Fitzwilliam","the Colonel"],
      mentions: 22, conf: 0.95, chapters: [30,31,32,33,34,35],
      summary: "Darcy 的表兄；在 Rosings 偶然透露 Darcy 拆散 Jane 与 Bingley 的事，触发 Elizabeth 拒婚。" },

    // Objects
    { id: "o01", type: "object", name: "Pemberley", zh: "潘伯里庄园",
      aliases: ["the great house","Mr. Darcy's house","Pemberley House","the estate"],
      mentions: 96, conf: 0.99, chapters: [9,10,16,25,33,35,42,43,44,45,46,47,52,55,60],
      summary: "Darcy 的德比郡庄园。第三十几章 Elizabeth 意外造访，是她对 Darcy 重新认识的物理场所。" },
    { id: "o02", type: "object", name: "Longbourn", zh: "朗博恩",
      aliases: ["home","my home","this estate","the estate"],
      mentions: 84, conf: 0.98, chapters: [1,7,13,15,21,23,26,41,47,49,55,57,59,61],
      summary: "班纳特家族在哈福德郡的居所，限定继承给最近的男性亲属（Collins）。" },
    { id: "o03", type: "object", name: "Netherfield Park", zh: "尼日斐花园",
      aliases: ["Netherfield","the house at Netherfield","that house"],
      mentions: 58, conf: 0.98, chapters: [1,3,5,7,8,9,10,11,12,13,17,21,55,57,59],
      summary: "Bingley 租下的庄园，位于 Longbourn 附近；情节开端。" },
    { id: "o04", type: "object", name: "Rosings Park", zh: "罗辛斯庄园",
      aliases: ["Rosings","Rosings Park","Lady Catherine's","her ladyship's house"],
      mentions: 56, conf: 0.98, chapters: [14,15,16,28,29,30,31,32,33,34,35,37],
      summary: "Lady Catherine 的肯特郡庄园；Darcy 第一次求婚发生于附近的 parsonage。" },
    { id: "o05", type: "object", name: "Darcy's letter", zh: "达西的信",
      aliases: ["the letter","Mr. Darcy's letter","this letter","what he wrote"],
      mentions: 38, conf: 0.97, chapters: [35,36,37,38,40,46,52],
      summary: "Darcy 在被拒后第二日交付的长信，澄清 Wickham 真相与 Jane / Bingley 分离的原因。全书结构枢轴。" },
    { id: "o06", type: "object", name: "the entail", zh: "限定继承",
      aliases: ["the entailment","entailed away","entail of the estate"],
      mentions: 14, conf: 0.96, chapters: [7,13,23,50],
      summary: "Longbourn 不能传女儿、必须传 Collins 的法律约束 —— 全书婚姻焦虑的制度根源。" },

    // Events
    { id: "v01", type: "event", name: "Bingley takes Netherfield", zh: "宾利租下尼日斐",
      aliases: ["Bingley arrives","let to Bingley"], mentions: 4, conf: 0.97, chapters: [1,2],
      summary: "情节开端事件 —— 单身富翁入住，引动 Mrs. Bennet 的全部行动。" },
    { id: "v02", type: "event", name: "the Meryton ball", zh: "梅里顿舞会",
      aliases: ["the assembly","the ball","at the ball"], mentions: 12, conf: 0.97, chapters: [3,4,5,6],
      summary: "Darcy 在此公开拒跳 Elizabeth，并说出「tolerable, but not handsome enough」。" },
    { id: "v03", type: "event", name: "first proposal at Hunsford", zh: "亨斯福德第一次求婚",
      aliases: ["the first proposal","at Hunsford","his proposal"], mentions: 6, conf: 0.98, chapters: [34,35],
      summary: "Darcy 在牧师宅邸向 Elizabeth 求婚，被以「the last man in the world」拒绝。" },
    { id: "v04", type: "event", name: "Lydia elopes with Wickham", zh: "莉迪亚与韦克翰私奔",
      aliases: ["the elopement","Lydia's flight","they are gone off together"], mentions: 18, conf: 0.97, chapters: [46,47,48,49,50,51],
      summary: "情节危机 —— 几乎毁掉所有 Bennet 女儿婚姻前景；Darcy 暗中出手解决。" },
    { id: "v05", type: "event", name: "Elizabeth visits Pemberley", zh: "伊丽莎白访潘伯里",
      aliases: ["the visit to Pemberley","Pemberley tour"], mentions: 8, conf: 0.96, chapters: [43,44,45],
      summary: "Elizabeth 随 Gardiners 误入 Pemberley，与 Darcy 重逢；她内心的「I never knew myself」之后的实地确认。" },
    { id: "v06", type: "event", name: "Lady Catherine confronts Elizabeth", zh: "凯瑟琳夫人对峙",
      aliases: ["that interview","her ladyship's visit"], mentions: 4, conf: 0.98, chapters: [56,57],
      summary: "Lady Catherine 闯入 Longbourn 要求 Elizabeth 承诺不嫁 Darcy；反讽地反向促成婚事。" },
    { id: "v07", type: "event", name: "second proposal", zh: "第二次求婚",
      aliases: ["the second proposal","he proposed again","walking with Mr. Darcy"], mentions: 4, conf: 0.98, chapters: [58,59],
      summary: "Elizabeth 与 Darcy 在田间散步时，他再次开口；这次被接受。" },
    { id: "v08", type: "event", name: "Collins's proposal to Charlotte", zh: "柯林斯向夏洛特求婚",
      aliases: ["Charlotte engaged","Collins proposes"], mentions: 4, conf: 0.96, chapters: [22],
      summary: "在被 Elizabeth 拒后 48 小时内，Collins 转向并被 Charlotte 接受。" },

    // Concepts
    { id: "c01", type: "concept", name: "pride", zh: "傲慢",
      aliases: ["pride","proud","his pride"], mentions: 38, conf: 0.96, chapters: [3,5,6,11,16,34,35,36,58],
      summary: "本书双题之一。Darcy 的阶级傲慢逐步显形与改写。" },
    { id: "c02", type: "concept", name: "prejudice", zh: "偏见",
      aliases: ["prejudice","prejudiced","my partiality"], mentions: 18, conf: 0.95, chapters: [16,17,34,36,42,58],
      summary: "Elizabeth 自承的偏见，「How despicably have I acted! I, who have prided myself on my discernment!」" },
    { id: "c03", type: "concept", name: "marriage", zh: "婚姻",
      aliases: ["matrimony","wedlock"], mentions: 28, conf: 0.96, chapters: [1,6,19,22,24,32,42,48,55,58,59,61],
      summary: "本书唯一真正的「世界设定」—— 不同婚姻模型（Charlotte / Lydia / Jane / Elizabeth）相互对照。" },
    { id: "c04", type: "concept", name: "social rank", zh: "门第 / 阶级",
      aliases: ["station","situation in life","rank","fortune","connection"], mentions: 22, conf: 0.95, chapters: [10,11,16,18,33,34,56],
      summary: "Lady Catherine 与 Caroline Bingley 反复援引的社会阶层 —— 全书的反讽对象。" },
    { id: "c05", type: "concept", name: "reputation", zh: "名声",
      aliases: ["reputation","good name","character","credit"], mentions: 16, conf: 0.94, chapters: [16,35,46,47,48,49,50],
      summary: "Lydia 私奔事件激活的核心概念 —— 一人之失污染整个家族婚姻市场。" },
    { id: "c06", type: "concept", name: "the entail / female disinheritance", zh: "女性不继承",
      aliases: [], mentions: 8, conf: 0.92, chapters: [7,13,23,50],
      summary: "把所有婚姻动力学固定在一个法律事实之上 —— 五个女儿生于无产权之家。" },
  ],

  // Edges — relationships
  edges: [
    { id: "ed01", src: "e02", dst: "e01", rel: "INTERACTS", label: "first slight", chunk: "ch3_p18", conf: 0.99, verified: true,
      evidence: "She is tolerable; but not handsome enough to tempt me; and I am in no humour at present to give consequence to young ladies who are slighted by other men.",
      claim: "Darcy 公开拒跳 Elizabeth，并称她「不够漂亮」—— Elizabeth 偏见的源头事件。" },
    { id: "ed02", src: "e01", dst: "c02", rel: "ASSERTS", label: "embodies", chunk: "ch36_p04", conf: 0.97, verified: true,
      evidence: "How despicably have I acted! I, who have prided myself on my discernment! How humiliating is this discovery! Till this moment, I never knew myself.",
      claim: "Elizabeth 读完 letter 后承认自己的偏见。" },
    { id: "ed03", src: "e02", dst: "c01", rel: "ASSERTS", label: "embodies", chunk: "ch11_p22", conf: 0.96, verified: true,
      evidence: "My good opinion once lost, is lost forever.",
      claim: "Darcy 在 Netherfield 自述其性情 —— 后被 Elizabeth 援引为「傲慢」证据。" },
    { id: "ed04", src: "e02", dst: "e01", rel: "INTERACTS", label: "first proposal", chunk: "ch34_p03", conf: 0.99, verified: true,
      evidence: "In vain I have struggled. It will not do. My feelings will not be repressed. You must allow me to tell you how ardently I admire and love you.",
      claim: "Darcy 在 Hunsford 牧师宅向 Elizabeth 求婚。" },
    { id: "ed05", src: "e01", dst: "e02", rel: "INTERACTS", label: "refuses", chunk: "ch34_p18", conf: 0.99, verified: true,
      evidence: "You are mistaken, Mr. Darcy, if you suppose that the mode of your declaration affected me in any other way than as it spared me the concern which I might have felt in refusing you...",
      claim: "Elizabeth 拒绝 Darcy 的求婚，斥其傲慢与对 Jane 的干预。" },
    { id: "ed06", src: "e02", dst: "o05", rel: "INTERACTS", label: "writes", chunk: "ch35_p01", conf: 0.99, verified: true,
      evidence: "Be not alarmed, Madam, on receiving this letter, by the apprehension of its containing any repetition of those sentiments, or renewal of those offers, which were last night so disgusting to you.",
      claim: "Darcy 在被拒次日撰写长信，澄清 Wickham 真相与对 Bingley/Jane 的干预。" },
    { id: "ed07", src: "o05", dst: "e10", rel: "ASSERTS", label: "exposes", chunk: "ch35_p14", conf: 0.98, verified: true,
      evidence: "Mr. Wickham's chief object was unquestionably my sister's fortune, which is thirty thousand pounds; but I cannot help supposing that the hope of revenging himself on me was a strong inducement.",
      claim: "letter 揭露 Wickham 曾企图诱拐十六岁的 Georgiana 以图三万英镑。" },
    { id: "ed08", src: "e07", dst: "e10", rel: "INTERACTS", label: "elopes with", chunk: "ch46_p04", conf: 0.99, verified: true,
      evidence: "My dear Lizzy, I have not the smallest objection to explaining them; but as it cannot be done without exposing my dearest sister... — Lydia is gone off to Scotland with one of his officers; to own the truth, with Wickham!",
      claim: "Lydia 与 Wickham 出逃伦敦，未婚同行 —— 全书结构危机。" },
    { id: "ed09", src: "e02", dst: "v04", rel: "INFLUENCES", label: "secretly resolves", chunk: "ch52_p08", conf: 0.97, verified: true,
      evidence: "It was owing to him, to his reserve and want of proper consideration, that Wickham's character had been so misunderstood... He came down on purpose, and submitted to all the mortifying conferences.",
      claim: "Darcy 暗中支付 Wickham 债务、安排婚姻、保全 Bennet 家族名声。" },
    { id: "ed10", src: "e11", dst: "e01", rel: "INTERACTS", label: "proposes (rejected)", chunk: "ch19_p02", conf: 0.98, verified: true,
      evidence: "Almost as soon as I entered the house, I singled you out as the companion of my future life.",
      claim: "Collins 向 Elizabeth 求婚，叙述其「合理化」理由；被坚决拒绝。" },
    { id: "ed11", src: "e11", dst: "e13", rel: "INTERACTS", label: "marries", chunk: "ch22_p10", conf: 0.97, verified: true,
      evidence: "She had only to wish it, and the affair was settled: they were to be married as soon as the licence could be procured.",
      claim: "在被 Elizabeth 拒后 48 小时内，Collins 转向 Charlotte 并被接受。" },
    { id: "ed12", src: "e13", dst: "c03", rel: "ASSERTS", label: "pragmatic view", chunk: "ch22_p14", conf: 0.96, verified: true,
      evidence: "I am not romantic, you know; I never was. I ask only a comfortable home; and considering Mr. Collins's character, connections, and situation in life, I am convinced that my chance of happiness with him is as fair as most people can boast on entering the marriage state.",
      claim: "Charlotte 阐明实用主义婚姻观，与 Elizabeth 形成对照。" },
    { id: "ed13", src: "e12", dst: "e01", rel: "INTERACTS", label: "confronts", chunk: "ch56_p14", conf: 0.98, verified: true,
      evidence: "I sent for you, that I might insist upon having such a report universally contradicted... that you should presume to aspire to it. ... You can now have nothing further to say.",
      claim: "Lady Catherine 闯入 Longbourn 试图阻止 Elizabeth 嫁给 Darcy。" },
    { id: "ed14", src: "e02", dst: "e01", rel: "INTERACTS", label: "second proposal", chunk: "ch58_p06", conf: 0.99, verified: true,
      evidence: "You are too generous to trifle with me. If your feelings are still what they were last April, tell me so at once. My affections and wishes are unchanged.",
      claim: "Darcy 在散步时第二次求婚，这次被接受。" },
    { id: "ed15", src: "e02", dst: "e04", rel: "INFLUENCES", label: "separated from Jane", chunk: "ch35_p08", conf: 0.97, verified: true,
      evidence: "I had not been long in Hertfordshire, before I saw, in common with others, that Bingley preferred your elder sister to any other young woman in the country. ... I determined to part them.",
      claim: "Darcy 主动说服 Bingley 离开 Jane —— 是 Elizabeth 拒婚的主因之一。" },
    { id: "ed16", src: "e06", dst: "e01", rel: "ASSERTS", label: "matrimonial pressure", chunk: "ch1_p02", conf: 0.96, verified: true,
      evidence: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
      claim: "全书第一句即建立了 Mrs. Bennet 的整个世界观与对女儿们的压力。" },
    { id: "ed17", src: "o02", dst: "o06", rel: "STRUCTURAL", label: "entailed by", chunk: "ch7_p04", conf: 0.95, verified: true,
      evidence: "Mr. Bennet's property consisted almost entirely in an estate of two thousand a year, which, unfortunately for his daughters, was entailed, in default of heirs male, on a distant relation.",
      claim: "Longbourn 限定继承给 Collins，构成全书婚姻焦虑的法律基础。" },
    { id: "ed18", src: "o01", dst: "e02", rel: "STRUCTURAL", label: "owned by", chunk: "ch43_p06", conf: 0.98, verified: true,
      evidence: "They had now entered a beautiful walk by the side of the water... at that moment she felt that to be mistress of Pemberley might be something!",
      claim: "Pemberley 是 Darcy 的庄园；它的「秩序、品味、克制」使 Elizabeth 重新理解他。" },
    { id: "ed19", src: "e01", dst: "v05", rel: "INTERACTS", label: "visits", chunk: "ch43_p02", conf: 0.97, verified: true,
      evidence: "Elizabeth, as they drove along, watched for the first appearance of Pemberley Woods with some perturbation; and when at length they turned in at the lodge, her spirits were in a high flutter.",
      claim: "Elizabeth 随 Gardiners 抵达 Pemberley，是与 Darcy 重逢的物理时空。" },
    { id: "ed20", src: "v06", dst: "v07", rel: "PREDICTS", label: "ironically triggers", chunk: "ch58_p02", conf: 0.94, verified: true,
      evidence: "It taught me to hope, as I had scarcely ever allowed myself to hope before. I knew enough of your disposition to be certain, that, had you been absolutely, irrevocably decided against me, you would have acknowledged it to Lady Catherine, frankly and openly.",
      claim: "Lady Catherine 的对峙反向证实 Elizabeth 态度松动，促使 Darcy 第二次开口。" },
    { id: "ed21", src: "e01", dst: "c01", rel: "INFLUENCES", label: "misjudges as", chunk: "ch5_p06", conf: 0.93, verified: true,
      evidence: "His pride does not offend me so much as pride often does, because there is an excuse for it. One cannot wonder that so very fine a young man, with family, fortune, every thing in his favour, should think highly of himself.",
      claim: "Charlotte 早期就指出 Darcy 的「傲慢」有阶级合理性 —— 为后续翻转埋伏笔。" },
    { id: "ed22", src: "e10", dst: "e01", rel: "ASSERTS", label: "lies about Darcy", chunk: "ch16_p12", conf: 0.97, verified: true,
      evidence: "I was destined for the church, and I should at this time have been in possession of a most valuable living, had it pleased the gentleman we were speaking of.",
      claim: "Wickham 向 Elizabeth 编造 Darcy 剥夺其遗产的故事，强化她的偏见。" },
    { id: "ed23", src: "e17", dst: "e01", rel: "ASSERTS", label: "reveals Darcy's role", chunk: "ch52_p04", conf: 0.97, verified: true,
      evidence: "Will you be very angry with me, my dear Lizzy, if I take this opportunity of saying (what I was never bold enough to say before) how much I like him? ... your uncle would have settled every thing.",
      claim: "Mrs. Gardiner 写信告知 Elizabeth：实际是 Darcy 解决了 Lydia 之事。" },
    { id: "ed24", src: "e07", dst: "c05", rel: "INFLUENCES", label: "endangers", chunk: "ch47_p10", conf: 0.96, verified: true,
      evidence: "We must endeavour to forget all that has passed on either side... but I am afraid the more we know of him, the worse we shall hear.",
      claim: "Lydia 的私奔威胁所有 Bennet 姐妹的婚姻市场。" },
  ],

  // GLUCOSE — 10-dim implicit facts
  glucose: [
    { entity: "e01", dim: "emotion · after",    depth: "explicit",
      text: "Elizabeth 读完 Darcy letter 的当下，感到强烈的羞愧与自责。",
      evidence: "Till this moment, I never knew myself.", chunk: "ch36_p04", conf: 0.97, verified: true },
    { entity: "e01", dim: "attribute · after",  depth: "multi_step",
      text: "Elizabeth 的「discernment（识人之明）」自我认知被 letter 直接否定。",
      evidence: "I, who have prided myself on my discernment!", chunk: "ch36_p04", conf: 0.92, verified: true },
    { entity: "e02", dim: "emotion · before",   depth: "one_step",
      text: "第一次求婚前 Darcy 内心冲突：傲慢与爱意拉锯。",
      evidence: "In vain I have struggled. It will not do.", chunk: "ch34_p03", conf: 0.94, verified: true },
    { entity: "e02", dim: "attribute · after",  depth: "multi_step",
      text: "letter 之后的 Darcy 不再援引阶级、隐身解决 Wickham 事件 —— 自我重塑。",
      evidence: "He came down on purpose... submitted to all the mortifying conferences.", chunk: "ch52_p08", conf: 0.88, verified: true },
    { entity: "e07", dim: "location · after",   depth: "explicit",
      text: "Lydia 出逃后位于伦敦某处，由 Darcy 寻获。",
      evidence: "Lydia is gone off to Scotland with... Wickham!", chunk: "ch46_p04", conf: 0.95, verified: true },
    { entity: "e10", dim: "possession · before", depth: "one_step",
      text: "Wickham 出逃前已积累显著赌债。",
      evidence: "His debts to be discharged, amounting, I believe, to considerably more than a thousand pounds.", chunk: "ch49_p06", conf: 0.91, verified: true },
    { entity: "e13", dim: "emotion · after",    depth: "multi_step",
      text: "Charlotte 与 Collins 婚后的「幸福」是策略性的、非情感性的。",
      evidence: "Charlotte said little. ... she had really no pleasure in talking of him.", chunk: "ch28_p06", conf: 0.83, verified: true },
    { entity: "e12", dim: "attribute · after",  depth: "one_step",
      text: "对峙失败之后，Lady Catherine 的权威遭受叙事性挫败。",
      evidence: "I take no leave of you, Miss Bennet. I send no compliments to your mother.", chunk: "ch56_p20", conf: 0.93, verified: true },
  ],

  // chunks — sampled portions of the text
  chunks: [
    { id: "ch1_p02", chapter: 1, seq: 2, tokens: 96, mentions: 0, edges: 1,
      text: `It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.\n\nHowever little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered as the rightful property of some one or other of their daughters.` },
    { id: "ch3_p18", chapter: 3, seq: 18, tokens: 142, mentions: 4, edges: 1,
      text: `"Which do you mean?" and turning round he looked for a moment at Elizabeth, till catching her eye, he withdrew his own and coldly said: "She is tolerable; but not handsome enough to tempt me; and I am in no humour at present to give consequence to young ladies who are slighted by other men. You had better return to your partner and enjoy her smiles, for you are wasting your time with me."\n\nMr. Bingley followed his advice. Mr. Darcy walked off; and Elizabeth remained with no very cordial feelings towards him.` },
    { id: "ch11_p22", chapter: 11, seq: 22, tokens: 112, mentions: 3, edges: 1,
      text: `"My good opinion once lost, is lost forever."\n\n"That is a failing indeed!" cried Elizabeth. "Implacable resentment is a shade in a character. But you have chosen your fault well. I really cannot laugh at it. You are safe from me."\n\n"There is, I believe, in every disposition a tendency to some particular evil, a natural defect, which not even the best education can overcome."` },
    { id: "ch34_p03", chapter: 34, seq: 3, tokens: 124, mentions: 2, edges: 1,
      text: `In a hurried manner he immediately began an inquiry after her health, imputing his visit to a wish of hearing that she were better. She answered him with cold civility. He sat down for a few moments, and then getting up, walked about the room. Elizabeth was surprised, but said not a word. After a silence of several minutes, he came towards her in an agitated manner, and thus began:\n\n"In vain I have struggled. It will not do. My feelings will not be repressed. You must allow me to tell you how ardently I admire and love you."` },
    { id: "ch36_p04", chapter: 36, seq: 4, tokens: 138, mentions: 2, edges: 1,
      text: `"How despicably have I acted!" she cried; "I, who have prided myself on my discernment! I, who have valued myself on my abilities! who have often disdained the generous candour of my sister, and gratified my vanity in useless or blameable distrust!—How humiliating is this discovery!—Yet, how just a humiliation!—Had I been in love, I could not have been more wretchedly blind. But vanity, not love, has been my folly.—Pleased with the preference of one, and offended by the neglect of the other, on the very beginning of our acquaintance, I have courted prepossession and ignorance, and driven reason away, where either were concerned. Till this moment, I never knew myself."` },
    { id: "ch58_p06", chapter: 58, seq: 6, tokens: 102, mentions: 2, edges: 1,
      text: `Elizabeth, feeling all the more than common awkwardness and anxiety of his situation, now forced herself to speak; and immediately, though not very fluently, gave him to understand that her sentiments had undergone so material a change, since the period to which he alluded, as to make her receive with gratitude and pleasure his present assurances. The happiness which this reply produced, was such as he had probably never felt before; and he expressed himself on the occasion as sensibly and as warmly as a man violently in love can be supposed to do.` },
  ],

  // Pipeline runs
  runs: [
    {
      bookId: "rose", status: "running", startedAt: "2026-05-27 09:18:04", currentPass: 5,
      passes: [
        { n: 1, name: "Chunk",    zh: "切片",       status: "done",    durationS: 4,    tokensIn: 0,      tokensOut: 0,     cachedIn: 0,      cost: 0.00, gleaning: null, output: "298 chunks · avg 880 tokens · 20% overlap" },
        { n: 2, name: "Entity",   zh: "实体抽取",   status: "done",    durationS: 712,  tokensIn: 312400, tokensOut: 84200, cachedIn: 251200, cost: 1.18, gleaning: 1.4, output: "2,184 mentions · gleaning avg 1.4 rounds" },
        { n: 3, name: "Cluster",  zh: "实体聚合",   status: "done",    durationS: 184,  tokensIn: 88200,  tokensOut: 12400, cachedIn: 0,      cost: 0.42, gleaning: null, output: "412 canonical entities · 1,872 alias merges" },
        { n: 4, name: "Coref",    zh: "共指消解",   status: "done",    durationS: 246,  tokensIn: 102400, tokensOut: 18600, cachedIn: 82000,  cost: 0.61, gleaning: null, output: "1,742 pronoun resolutions" },
        { n: 5, name: "Relation", zh: "关系 + 事件", status: "running", durationS: 488,  tokensIn: 198400, tokensOut: 41200, cachedIn: 158000, cost: 1.42, gleaning: 1.1, output: "edge extraction · chunk 192 / 298" },
        { n: 6, name: "GLUCOSE",  zh: "隐式信息",   status: "queued",  durationS: 0,    tokensIn: 0,      tokensOut: 0,     cachedIn: 0,      cost: 0.00, gleaning: null, output: null },
        { n: 7, name: "CoVe",     zh: "字面验证",   status: "queued",  durationS: 0,    tokensIn: 0,      tokensOut: 0,     cachedIn: 0,      cost: 0.00, gleaning: null, output: null },
      ],
      logs: [
        { t: "09:18:04", level: "info",  msg: "run started · book #2 · provider deepseek · model deepseek-chat" },
        { t: "09:18:08", level: "info",  msg: "Pass-1 chunking · 298 chunks emitted · atom_id range ch1_p01 → ch7_p42" },
        { t: "09:30:00", level: "info",  msg: "Pass-2 done · 2,184 mentions · cache hit rate 80.4%" },
        { t: "09:33:04", level: "info",  msg: "Pass-3 done · 412 canonical entities · 1,872 aliases merged" },
        { t: "09:37:10", level: "warn",  msg: "Pass-4 · low-confidence pronoun cluster at ch4_p12 (conf 0.52) — fell back to LLM judge" },
        { t: "09:37:46", level: "info",  msg: "Pass-4 done · 1,742 pronoun resolutions written" },
        { t: "09:39:00", level: "info",  msg: "Pass-5 started · processing chunks in 12-way parallel batches" },
        { t: "09:46:18", level: "info",  msg: "Pass-5 · 192/298 chunks · 1,142 edges so far · realis-trigger filter removed 218" },
        { t: "09:46:42", level: "warn",  msg: "Pass-5 · ch4_p33 emitted 0 edges — flagging for manual review" },
      ],
    },
    {
      bookId: "pap", status: "verified", startedAt: "2026-05-26 09:14:00", finishedAt: "2026-05-26 09:38:42", currentPass: 7,
      passes: [
        { n: 1, name: "Chunk",    zh: "切片",       status: "done", durationS: 6,   tokensIn: 0,      tokensOut: 0,    cachedIn: 0,      cost: 0.00, gleaning: null, output: "248 chunks · avg 654 tokens · 20% overlap" },
        { n: 2, name: "Entity",   zh: "实体抽取",   status: "done", durationS: 412, tokensIn: 198400, tokensOut: 52400, cachedIn: 159000, cost: 0.84, gleaning: 1.2, output: "1,684 mentions · 4 types" },
        { n: 3, name: "Cluster",  zh: "实体聚合",   status: "done", durationS: 86,  tokensIn: 28200,  tokensOut: 4200,  cachedIn: 0,      cost: 0.18, gleaning: null, output: "38 canonical entities · 642 aliases merged" },
        { n: 4, name: "Coref",    zh: "共指消解",   status: "done", durationS: 132, tokensIn: 62400,  tokensOut: 12600, cachedIn: 51200,  cost: 0.32, gleaning: null, output: "1,142 pronoun resolutions" },
        { n: 5, name: "Relation", zh: "关系 + 事件", status: "done", durationS: 384, tokensIn: 142400, tokensOut: 32800, cachedIn: 120000, cost: 0.78, gleaning: 1.0, output: "124 edges · 8 realis events · 142 filtered as non-realis" },
        { n: 6, name: "GLUCOSE",  zh: "隐式信息",   status: "done", durationS: 268, tokensIn: 98800,  tokensOut: 26400, cachedIn: 82400,  cost: 0.42, gleaning: null, output: "412 GLUCOSE facts · 5 dims × 2 time × 38 entities" },
        { n: 7, name: "CoVe",     zh: "字面验证",   status: "done", durationS: 224, tokensIn: 88200,  tokensOut: 11400, cachedIn: 78000,  cost: 0.30, gleaning: null, output: "match rate 0.971 ✓ above threshold · 18 claims rewritten" },
      ],
      matchRate: 0.971,
      totalCost: 2.84,
      totalTokens: 618400,
    }
  ],

  // ask queries
  conversations: [
    {
      q: "What changes Elizabeth's view of Darcy from prejudice to admiration?",
      a: "Elizabeth 对 Darcy 的态度并非一次翻转，而是 **三个事件 + 一封信** 的累积过程：",
      points: [
        { text: "ch34 的求婚是触发器 —— 她在拒绝中第一次完整表达自己对他的偏见。", chunk: "ch34_p03", entity: "e02", edge: "ed04" },
        { text: "ch35 的 letter 提供反证据：Wickham 的真面目 + 拆散 Jane 的诚实坦白。", chunk: null, entity: "o05", edge: "ed06" },
        { text: "ch36 她独自承认偏见：「Till this moment, I never knew myself.」这是态度松动的内核。", chunk: "ch36_p04", entity: "e01", edge: "ed02" },
        { text: "ch43 Pemberley 之行：她以管家口中、以建筑秩序、以待人方式重新认识他。", chunk: null, entity: "o01", edge: "ed19" },
        { text: "ch52 Mrs. Gardiner 信件揭示 Darcy 暗中解决 Lydia 之事 —— 最后一块拼图。", chunk: null, entity: "e17", edge: "ed23" },
      ],
      caveat: "本回答完全基于本书内部提及。Pass-6 GLUCOSE 在 attribute · after 维度的 multi_step 推断对 Darcy 的「自我重塑」给出 conf 0.88 —— 强但非 explicit。",
    },
    {
      q: "Map the four marriage models in the novel.",
      a: "全书在四对婚姻中检验「what makes a good marriage」—— 这是 Austen 用来批判 Mrs. Bennet 单一逻辑的结构性手段：",
      points: [
        { text: "Charlotte ↔ Collins：策略型 —— 婚姻作为经济独立的手段，无情感成本。", chunk: "ch22_p14", entity: "e13", edge: "ed12" },
        { text: "Lydia ↔ Wickham：冲动型 —— 性吸引 + 虚荣，被 Darcy 用金钱强行「修复」。", chunk: "ch46_p04", entity: "e07", edge: "ed08" },
        { text: "Jane ↔ Bingley：温和型 —— 真感情但缺乏自主性，几乎被外力拆散。", chunk: null, entity: "e03", edge: "ed15" },
        { text: "Elizabeth ↔ Darcy：变革型 —— 双方都为对方改变；唯一通过「self-knowledge」抵达的婚姻。", chunk: "ch58_p06", entity: "e01", edge: "ed14" },
      ],
      caveat: "Pass-5 把所有四桩婚姻都识别为 realis event；唯有 Wickham/Lydia 的 INTERACTS 边附带显著的负向 GLUCOSE（emotion · after, conf 0.91）。",
    },
    {
      q: "Why does Lady Catherine's confrontation backfire?",
      a: "Lady Catherine 在 ch56 闯入 Longbourn，明确要 Elizabeth 承诺不嫁 Darcy。Elizabeth 拒绝承诺。这场对峙 **本意是阻止婚姻，事实上却促成了它**：",
      points: [
        { text: "Elizabeth 在对峙中没有否认对 Darcy 的感情，这本身就构成 Darcy 可读的信号。", chunk: "ch56_p14", entity: "e12", edge: "ed13" },
        { text: "Lady Catherine 把事件转述给 Darcy，意图借家族压力切断。", chunk: null, entity: "e12" },
        { text: "Darcy 在 ch58 直接引用此事作为「重新开口」的依据：「had you been absolutely decided against me, you would have acknowledged it」。", chunk: "ch58_p06", entity: "e02", edge: "ed20" },
      ],
      caveat: "Pass-5 把 ch56→ch58 标为 PREDICTS 边（conf 0.94），是本书反讽因果链的一条 textbook 案例。",
    },
  ],
};

// ===== Per-locale book titles =====
window.LG_BOOK_TITLES = {
  pap: {
    "en":    "Pride and Prejudice",
    "zh-CN": "傲慢与偏见",
    "zh-TW": "傲慢與偏見",
    "ja":    "高慢と偏見",
    "ko":    "오만과 편견",
    "fr":    "Orgueil et préjugés",
    "es":    "Orgullo y prejuicio",
    "de":    "Stolz und Vorurteil",
  },
  rose: {
    "en":    "The Name of the Rose",
    "zh-CN": "玫瑰之名",
    "zh-TW": "玫瑰之名",
    "ja":    "薔薇の名前",
    "ko":    "장미의 이름",
    "fr":    "Le Nom de la rose",
    "es":    "El nombre de la rosa",
    "de":    "Der Name der Rose",
  },
  frank: {
    "en":    "Frankenstein",
    "zh-CN": "弗兰肯斯坦",
    "zh-TW": "科學怪人",
    "ja":    "フランケンシュタイン",
    "ko":    "프랑켄슈타인",
    "fr":    "Frankenstein",
    "es":    "Frankenstein",
    "de":    "Frankenstein",
  },
  drac: {
    "en":    "Dracula",
    "zh-CN": "德古拉",
    "zh-TW": "德古拉",
    "ja":    "ドラキュラ",
    "ko":    "드라큘라",
    "fr":    "Dracula",
    "es":    "Drácula",
    "de":    "Dracula",
  },
  alice: {
    "en":    "Alice's Adventures in Wonderland",
    "zh-CN": "爱丽丝梦游仙境",
    "zh-TW": "愛麗絲夢遊仙境",
    "ja":    "不思議の国のアリス",
    "ko":    "이상한 나라의 앨리스",
    "fr":    "Les Aventures d'Alice au pays des merveilles",
    "es":    "Las aventuras de Alicia en el País de las Maravillas",
    "de":    "Alice im Wunderland",
  },
  mob: {
    "en":    "Moby-Dick",
    "zh-CN": "白鲸",
    "zh-TW": "白鯨",
    "ja":    "白鯨",
    "ko":    "모비 딕",
    "fr":    "Moby Dick",
    "es":    "Moby Dick",
    "de":    "Moby-Dick",
  },
};

window.bookTitle = function(book, locale) {
  const L = locale || window.__lg_locale || "en";
  const map = window.LG_BOOK_TITLES[book.id];
  if (map && map[L]) return map[L];
  if (map && map.en) return map.en;
  // Fallback to whatever is on the book object.
  if ((L === "zh-CN" || L === "zh-TW" || L === "ja" || L === "ko") && book.titleZh) return book.titleZh;
  return book.title;
};

window.LG_BOOK_AUTHORS = {
  pap:   { "en": "Jane Austen",     "zh-CN": "简·奥斯汀",       "zh-TW": "珍·奧斯汀",       "ja": "ジェーン・オースティン", "ko": "제인 오스틴",     "fr": "Jane Austen",     "es": "Jane Austen",     "de": "Jane Austen" },
  rose:  { "en": "Umberto Eco",     "zh-CN": "翁贝托·埃科",     "zh-TW": "安伯托·艾可",     "ja": "ウンベルト・エーコ",     "ko": "움베르토 에코",   "fr": "Umberto Eco",     "es": "Umberto Eco",     "de": "Umberto Eco" },
  frank: { "en": "Mary Shelley",    "zh-CN": "玛丽·雪莱",       "zh-TW": "瑪麗·雪萊",       "ja": "メアリー・シェリー",     "ko": "메리 셸리",       "fr": "Mary Shelley",    "es": "Mary Shelley",    "de": "Mary Shelley" },
  drac:  { "en": "Bram Stoker",     "zh-CN": "布拉姆·斯托克",   "zh-TW": "布拉姆·斯托克",   "ja": "ブラム・ストーカー",     "ko": "브램 스토커",     "fr": "Bram Stoker",     "es": "Bram Stoker",     "de": "Bram Stoker" },
  alice: { "en": "Lewis Carroll",   "zh-CN": "刘易斯·卡罗尔",   "zh-TW": "路易斯·卡羅",     "ja": "ルイス・キャロル",       "ko": "루이스 캐럴",     "fr": "Lewis Carroll",   "es": "Lewis Carroll",   "de": "Lewis Carroll" },
  mob:   { "en": "Herman Melville", "zh-CN": "赫尔曼·梅尔维尔", "zh-TW": "赫爾曼·梅爾維爾", "ja": "ハーマン・メルヴィル",   "ko": "허먼 멜빌",       "fr": "Herman Melville", "es": "Herman Melville", "de": "Herman Melville" },
};

window.bookAuthor = function(book, locale) {
  const L = locale || window.__lg_locale || "en";
  const map = window.LG_BOOK_AUTHORS[book.id];
  if (map && map[L]) return map[L];
  if (map && map.en) return map.en;
  return book.author;
};
